public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
        byte orange = 5;
        System.out.println("Значение переменной orange с типом byte равно " + orange);
        short apple = 75;
        System.out.println("Значение переменной apple с типом short равно " + apple);
        int pear = 275;
        System.out.println("Значение переменной pear с типом int равно " + pear);
        long pineapple = 1222275;
        System.out.println("Значение переменной pineapple с типом long равно " + pineapple);
        float strawberry = 15.36F;
        System.out.println("Значение переменной strawberry с типом float равно " + strawberry);
        double coconut = 685.7956;
        System.out.println("Значение переменной coconut с типом double равно " + coconut);
        float a = 27.12F;
        System.out.println(a + " относится к типу float");
        float b = 2.786F;
        System.out.println(b + " относится к типу float");
        short c = 569;
        System.out.println(c + " относится к типу short");
        short d = -159;
        System.out.println(d + " относится к типу short");
        int e = 27897;
        System.out.println(e + " относится к типу int");
        byte f = 67;
        System.out.println(f + " относится к типу byte");
        long h = 987678965549L;
        System.out.println(h + " относится к типу long");
        byte teacherLP = 23;
        byte teacherAS = 27;
        byte teacherEA = 30;
        int paper = 480;
        int paperStudent = paper / (teacherLP + teacherAS + teacherEA);
        System.out.println("На каждого ученика рассчитано " + paperStudent + " листов бумаги");
        byte initialPerformance = 16;
        byte initialTime = 2;
        byte time1 = 20;
        short time2 = 1440;
        short time3 = 4320;
        int time4 = 43200;
        int performance1 = (initialPerformance / initialTime) * time1;
        System.out.println("За " + time1 + " минут машина произвела " + performance1 + " штук бутылок ");
        int performance2 = (initialPerformance / initialTime) * time2;
        System.out.println("За " + time2 + " минут машина произвела " + performance2 + " штук бутылок ");
        int performance3 = (initialPerformance / initialTime) * time3;
        System.out.println("За " + time3 + " минут машина произвела " + performance3 + " штук бутылок ");
        int performance4 = (initialPerformance / initialTime) * time4;
        System.out.println("За " + time4 + " минут машина произвела " + performance4 + " штук бутылок ");
        byte totalDye = 120;
        byte whiteDye = 2;
        byte brownDye = 4;
        int totalClass = totalDye / (whiteDye + brownDye);
        int totalWhite = whiteDye * totalClass;
        int totalBrown = brownDye * totalClass;
        System.out.println("В школе, где " + totalClass + " классов, нужно " + totalWhite + " банок белой краски и " + totalBrown + " банок коричневой краски");
        byte banana = 80;
        byte milk = 105;
        byte iceCream = 100;
        byte egg = 70;
        byte numberBanana = 5;
        byte numberMilk = 2;
        byte numberIceCream = 2;
        byte numberEgg = 4;
        int breakfast = banana * numberBanana + milk * numberMilk + iceCream * numberIceCream + egg * numberEgg;
        float breakfastKg = breakfast / 1000;
        System.out.println(" Вес в грамма составляет " + breakfast + " грамм или " + breakfastKg +  " кг");

        int totalWeight = 7;
        int var1 = 250;
        int var2 = 500;
        int day1 = totalWeight * 1000 / var1;
        int day2 = totalWeight * 1000/ var2;
        float dayMiddle = totalWeight * 1000 / (var1 + var2);
        System.out.println("Похудение на " + var1 + " грамм в день займет " + day1 + " дней");
        System.out.println("Похудение на " + var2 + " грамм в день займет " + day2 + " дней");
        System.out.println("Похудение в среднем займет " + dayMiddle + " дней");

        int salaryMasha1 = 67760;
        int salaryDenis1 = 83690;
        int salaryKristina1 = 76230;
        double salaryMasha2 = salaryMasha1 * 1.1;
        double salaryDenis2 = salaryDenis1 * 1.1;
        double salaryKristina2 = salaryKristina1 * 1.1;
        double diffMasha = salaryMasha2 - salaryMasha1;
        double diffDenis = salaryDenis2 - salaryDenis1;
        double diffKristina = salaryKristina2 - salaryKristina1;
        System.out.println("Маша теперь получает " + salaryMasha2 + " рублей. Годовой доход вырос на " + diffMasha + " рублей");
        System.out.println("Денис теперь получает " + salaryDenis2 + " рублей. Годовой доход вырос на " + diffDenis + " рублей");
        System.out.println("Кристина теперь получает " + salaryKristina2 + " рублей. Годовой доход вырос на " + diffKristina + " рублей");

    }
}